language: node_js
node_js:
  - '7'
before_install:
  - 'npm install -g npm@latest'
services:
  - mongodb
before_script:
  - sleep 10
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
